-- Run this in Supabase SQL Editor to create the table
create table if not exists sensor_readings (
  id bigint generated by default as identity primary key,
  temperature float,
  humidity float,
  soil_moisture int,
  light float,
  timestamp timestamp default now()
);
